let g:v_path = escape(fnamemodify(resolve(expand("<sfile>:p")), ":h"), ' ')

" pathogen
exe 'source ' . g:v_path . '/core/pathogen/autoload/pathogen.vim'
execute pathogen#infect(g:v_path . '/plugins/{}', g:v_path . '/colors/{}')

if filereadable(expand("~/.vimrc.before"))
  source ~/.vimrc.before
endif

" we are millenials
set nocompatible

set nomodeline

" please no
set belloff=all

set nowrap
set tabstop=4
set softtabstop=4
set expandtab
set autoindent
set smartindent
set shiftwidth=4
set number
set scrolloff=4
set backspace=indent,eol,start

" lots of undos
set history=100
set undolevels=100

set nobackup
set noswapfile

" search
set incsearch
set ignorecase
set smartcase
set hlsearch

" filename auto-complete
set wildmode=list:longest

if exists('+colorcolumn')
    set colorcolumn=80
endif

" highlight cursor line
set cursorline

" split vertical windows below
set splitbelow

" visual select after tab/untab
vnoremap <Tab> >gv
vnoremap <S-Tab> <gv

filetype indent plugin on
syntax enable

if has('gui_running')
    set guioptions-=T
endif

if has('statusline')
    " always display statusline
    set laststatus=2

    " customize
    set statusline=%f
    set statusline+=%=
    set statusline+=\ %#warningmsg#
    set statusline+=%{SyntasticStatuslineFlag()}%*\ [%P]
endif

nnoremap <leader>n :NERDTreeToggle<CR>
nnoremap <leader><space> :nohlsearch<CR>
" avoid unindenting from smartindent
inoremap # X#

if filereadable(expand("~/.vimrc.after"))
  source ~/.vimrc.after
endif
